Extend test to cover browser access
There's something broken with icon-shim/folders, so remove that dependency.

Caused by: java.lang.NoSuchMethodError: org.jenkins.ui.icon.IconSet.getIconByClassSpec(Ljava/lang/Object;)Lorg/jenkins/ui/icon/Icon;
	at com.cloudbees.hudson.plugins.folder.FolderIcon.iconClassNameImageOf(FolderIcon.java:79)
	at com.cloudbees.hudson.plugins.folder.icons.StockFolderIcon.getImageOf(StockFolderIcon.java:48)

Call to #getIconByClassSpec(Object):
https://github.com/jenkinsci/cloudbees-folder-plugin/commit/9c718a0f35c3746d66c9786fd957eaeaaab2d2b5#diff-b49f1321eeee69fc8ea22bad0386ee37R79
breaks apparently due to:
https://github.com/jenkinsci/icon-shim-plugin/commit/1d358279ad0058a2a47ceffca5901c4de81c2aec#diff-f6777df3e4df7526e2af135330fca04dL103